### ISSUE TITLE
To contribute, some additions to testing

### ISSUE THREAD

**Issue by MarkvanOsch** [devoxx/JavaRoadmap2022#1]
Good to know.

Testing: 
- Contract testing 
   - Spring contract
   -  Pact 
   
E2E testing: 
- Karate

Unit testing:
- TDD/BDD

**Comment by rodrigolopes** [comment]
add a link between REST and Testing; and add RestAssure and Wiremock

**Comment by rodrigolopes** [comment]
TDD/BDD should be in General Programming Skills

**Comment by stephanj** [comment]
RestAssure and Wiremock added to V7, thanks for pointing these out!

**Comment by shelajev** [comment]
Can Testcontainers be added to integration testing please. If possible can be connected to Docker.

**Comment by MarkvanOsch** [comment]
[stephanj](/stephanj) could these also be added please? All with good to know label in my view.

> Testing:
> * Contract testing
>   * Spring contract
>   * Pact
> 
> E2E testing:
> * Karate
> 
> General Programming Skills:
> * DDD: Domain Driven Design
> * BDD: Behaviour Driven Development
> * TDD: Test Driven Development

**Comment by stephanj** [comment]
Testcontainers added as well as DDD / TDD

**Comment by MarkvanOsch** [comment]
Thanks for the updates. One more useful addition to REST testing is Karate for easy BDD style API Rest testing: https://github.com/karatelabs/karate

<img width="645" alt="image" src="https://user-images.githubusercontent.com/41586088/162687318-5aaccf3b-3359-4e72-98f4-39e905c0edb6.png">

**Comment by stephanj** [comment]
Karate added to latest version
