### ISSUE TITLE
Hibernate is not a framework

### ISSUE THREAD

**Issue by aruizca** [devoxx/JavaRoadmap2022#2]
It is the JPA reference implementation and therefore should be part of database persistence and as part of the database node

**Comment by aruizca** [comment]
It also support querying using with SQL. It should be a tool/library to access DB using JPA spec and sitting close to Jooq albeit they have different approaches to querying a relational DB.

**Comment by stephanj** [comment]
What about this refactoring?

See also https://twitter.com/Devoxx/status/1512804485831213061 

![image](https://user-images.githubusercontent.com/179457/162579369-eed4b0f7-9cd6-48ae-97ee-34f74a5f6c09.png)

And removing "Database persistence" from frameworks?

![image](https://user-images.githubusercontent.com/179457/162575997-0c6881a4-da92-43c4-b71b-d866305c03f4.png)

Comments & suggestions welcome!

**Comment by aruizca** [comment]
Much better!! But Hibernate also supports SQL through JDBC, and it is a common misconception that your diagram could also help to clarify. So does Spring Data

**Comment by stephanj** [comment]
Voila

![image](https://user-images.githubusercontent.com/179457/162628657-f60477d2-d0f9-4201-b975-9e2c41a602c8.png)

**Comment by aruizca** [comment]
Thanks @stephanj
